services:
    # 后端服务
    ktv-web-backend:
        build:
            context: .
            dockerfile: backend/Dockerfile # 指向后端的 Dockerfile 路径
        image: ghcr.io/starfreedomx/ktv-song-web-backend:latest
        container_name: ktv-web-backend
        restart: always
        depends_on:
            - redis

    # 前端服务
    ktv-web-frontend:
        build:
            context: .
            dockerfile: frontend/Dockerfile # 指向前端的 Dockerfile 路径
        image: ghcr.io/starfreedomx/ktv-song-web-frontend:latest
        container_name: ktv-web-frontend
        restart: always
        ports:
            - "5526:5526"
        depends_on:
            - ktv-web-backend

    # Redis 数据库
    redis:
        image: redis:alpine
        container_name: ktv-web-redis
        restart: always
        command: redis-server --appendonly yes
        volumes:
            - redis_data:/data

volumes:
    redis_data:
